catalogs:
  web:
    "@sveltejs/kit": "2.8.1"
    "svelte": "5.2.0"
    "@sveltejs/adapter-node": "5.2.9"
    "@sveltejs/vite-plugin-svelte": "4.0.0"
    "svelte-check": "4.0.8"
    "vite": "5.4.11"
    "vitest": "2.1.5"
    "@playwright/test": "1.48.2"
    "globals": "15.12.0"
    "xstate": "5.19.0"
    "@inlang/paraglide-js": "1.11.3"
    "inter-ui": "4.0.2"
    "@inlang/paraglide-sveltekit": "0.11.5"
    "ws": "8.18.0"
    "nanoid": "5.0.8"
  specs:
    "c8": "10.1.2"
    "monocart-coverage-reports": "2.11.2"
  utils:
    "@swc/core": "1.9.2"
    "@swc/cli": "0.5.0"
    "@eslint/js": "9.14.0"
    "eslint": "9.14.0"
    "eslint-config-prettier": "9.1.0"
    "eslint-plugin-svelte": "2.46.0"
    "eslint-config-airbnb-base": "15.0.0"
    "eslint-plugin-import": "2.31.0"
    "eslint-plugin-node": "11.1.0"
    "@types/eslint": "9.6.1"
    "prettier": "3.3.3"
    "typescript": "5.6.3"
    "flatbuffers": "24.3.25"
    "renamer": "5.0.2"
    "typescript-eslint": "8.14.0"
    "execa": "9.5.1"
    "which": "5.0.0"
packages:
  - 'sources/**'
  - 'libs/**'
  - 'experiments/**'