catalogs:
  web:
    "@sveltejs/kit": "2.8.5"
    "svelte": "5.2.10"
    "@sveltejs/adapter-node": "5.2.9"
    "@sveltejs/vite-plugin-svelte": "5.0.1"
    "svelte-check": "4.1.0"
    "vite": "6.0.1"
    "vitest": "2.1.6"
    "@playwright/test": "1.49.0"
    "globals": "15.12.0"
    "xstate": "5.19.0"
    "@inlang/paraglide-js": "1.11.3"
    "inter-ui": "4.1.0"
    "@inlang/paraglide-sveltekit": "0.12.1"
    "ws": "8.18.0"
    "nanoid": "5.0.9"
  specs:
    "c8": "10.1.2"
    "monocart-coverage-reports": "2.11.3"
  utils:
    "@swc/core": "1.9.3"
    "@swc/cli": "0.5.1"
    "@eslint/js": "9.15.0"
    "eslint": "9.15.0"
    "eslint-config-prettier": "9.1.0"
    "eslint-plugin-svelte": "2.46.0"
    "eslint-config-airbnb-base": "15.0.0"
    "eslint-plugin-import": "2.31.0"
    "eslint-plugin-node": "11.1.0"
    "@types/eslint": "9.6.1"
    "prettier": "3.4.1"
    "typescript": "5.7.2"
    "renamer": "5.0.2"
    "typescript-eslint": "8.16.0"
    "execa": "9.5.1"
    "which": "5.0.0"
  server:
    "koffi": "^2.9.2"
packages:
  - 'sources/**'
  - 'libs/**'
  - 'experiments/**'
  - 'tools/**'
  - 'out.ts/**'