catalogs:
  web:
    "@sveltejs/kit": "^2.5.28"
    "svelte": "5.0.0-next.206"
    "@sveltejs/adapter-node": "^5.2.4"
    "@sveltejs/vite-plugin-svelte": "^4.0.0-next.4"
    "svelte-check": "4.0.2"
    "vite": "^5.4.7"
    "vitest": "^2.1.1"
    "@playwright/test": "^1.47.2"
    "globals": "^15.9.0"
    "xstate": "^5.18.2"
    "@inlang/paraglide-js": "1.11.2"
    "inter-ui": "^4.0.2"
    "@inlang/paraglide-sveltekit": "0.11.0"
    "ws": "^8.18.0"
    "nanoid": "^5.0.7"
  server:
    "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.47.0"
  specs:
    "c8": "^10.1.2"
    "monocart-coverage-reports": "2.10.9"
  utils:
    "@swc/core": "^1.7.26"
    "@swc/cli": "^0.4.1-nightly.20240914"
    "@eslint/js": "^9.11.0"
    "eslint": "^9.11.0"
    "eslint-config-prettier": "^9.1.0"
    "eslint-plugin-svelte": "2.44.0"
    "eslint-config-airbnb-base": "^15.0.0"
    "eslint-plugin-import": "^2.30.0"
    "eslint-plugin-node": "^11.1.0"
    "@types/eslint": "9.6.1"
    "prettier": "^3.3.3"
    "typescript": "^5.6.2"
    "flatbuffers": "^24.3.25"
    "renamer": "^5.0.2"
    "typescript-eslint": "8.6.0"
    "execa": "^9.4.0"
    "which": "^4.0.0"
packages:
  - 'sources/**'