catalogs:
  web:
    "@sveltejs/kit": "2.6.4"
    "svelte": "5.0.0-next.206"
    "@sveltejs/adapter-node": "5.2.6"
    "@sveltejs/vite-plugin-svelte": "4.0.0-next.4"
    "svelte-check": "4.0.4"
    "vite": "5.4.8"
    "vitest": "2.1.2"
    "@playwright/test": "1.48.0"
    "globals": "15.11.0"
    "xstate": "5.18.2"
    "@inlang/paraglide-js": "1.11.3"
    "inter-ui": "4.0.2"
    "@inlang/paraglide-sveltekit": "0.11.1"
    "ws": "8.18.0"
    "nanoid": "5.0.7"
  server:
    "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.47.0"
  specs:
    "c8": "10.1.2"
    "monocart-coverage-reports": "2.11.1"
  utils:
    "@swc/core": "1.7.35"
    "@swc/cli": "0.4.1-nightly.20240914"
    "@eslint/js": "9.12.0"
    "eslint": "9.12.0"
    "eslint-config-prettier": "9.1.0"
    "eslint-plugin-svelte": "2.44.1"
    "eslint-config-airbnb-base": "15.0.0"
    "eslint-plugin-import": "2.31.0"
    "eslint-plugin-node": "11.1.0"
    "@types/eslint": "9.6.1"
    "prettier": "3.3.3"
    "typescript": "5.6.3"
    "flatbuffers": "24.3.25"
    "renamer": "5.0.2"
    "typescript-eslint": "8.8.1"
    "execa": "9.4.0"
    "which": "5.0.0"
packages:
  - 'sources/**'