catalogs:
  web:
    "@sveltejs/kit": "^2.5.18"
    "svelte": "5.0.0-next.193"
    "@sveltejs/adapter-auto": "^3.2.2"
    "@sveltejs/adapter-node": "^5.2.0"
    "@sveltejs/adapter-static": "^3.0.2"
    "@sveltejs/vite-plugin-svelte": "^4.0.0-next.4"
    "svelte-check": "^3.8.4"
    "vite": "^5.3.4"
    "vitest": "^2.0.3"
    "@playwright/test": "^1.45.2"
    "@types/eslint": "^8.56.10"
    "eslint": "^9.7.0"
    "eslint-config-prettier": "^9.1.0"
    "eslint-plugin-svelte": "2.43.0"
    "globals": "^15.8.0"
    "prettier": "^3.3.3"
    "typescript": "^5.5.3"
    "xstate": "^5.15.0"
    "@inlang/paraglide-js": "1.11.2"
    "inter-ui": "^4.0.2"
    "@inlang/paraglide-sveltekit": "0.10.10"
    "flatbuffers": "^24.3.25"
    "c8": "^10.1.2"
    "chai": "^5.1.1"
    "eslint-config-airbnb-base": "^15.0.0"
    "eslint-plugin-chai-friendly": "^1.0.0"
    "eslint-plugin-import": "^2.29.1"
    "eslint-plugin-node": "^11.1.0"
    "mocha": "^10.7.0"
    "ws": "^8.18.0"

packages:
  - 'sources/**'