catalogs:
  web:
    "@sveltejs/kit": "^2.5.18"
    "svelte": "5.0.0-next.190"
    "@sveltejs/adapter-auto": "^3.2.2"
    "@sveltejs/adapter-node": "^5.2.0"
    "@sveltejs/adapter-static": "^3.0.2"
    "@sveltejs/vite-plugin-svelte": "^3.1.1"
    "svelte-check": "^3.8.4"
    "vite": "^5.3.3"
    "vitest": "^1.6.0"
    "@playwright/test": "^1.45.1"
    "@types/eslint": "^8.56.10"
    "eslint": "^9.6.0"
    "eslint-config-prettier": "^9.1.0"
    "eslint-plugin-svelte": "2.41.0"
    "globals": "^15.8.0"
    "prettier": "^3.3.2"
    "typescript": "^5.5.3"
    "xstate": "^5.14.0"
    "@inlang/paraglide-js": "1.11.1"
    "inter-ui": "^4.0.2"
    "@inlang/paraglide-sveltekit": "0.10.10"

packages:
  - 'sources/**'