name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup Please
        uses: sagikazarmark/setup-please-action@v0
        with:
          output: all
          verbosity: debug
      
      - name: build
        run: plz build
