name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: bazel-contrib/setup-bazel@0.9.0
        with:
          bazelisk-cache: true
          repository-cache: true
          external-cache: |
            manifest:
              npm: pnpm-lock.yaml
      - run: bazel build //...
      # - run: bazel test //...

