name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    env:
      PNPM_STORE_PATH: .pnpm-store
    runs-on: ubuntu-24.04
    defaults:
      run: 
        shell: bash
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.1
          run_install: false
          standalone: true
      
      # - name: configure PNPM
      #   run: |
      #     pnpm config set store-dir $PNPM_STORE_PATH
      
      # - name: restore pnpm cache
      #   id: pnpm-cache-restore
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: $PNPM_STORE_PATH
      #     key: ${{ runner.os }}-pnpm-cache

      - name: install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
      
      - name: setup Please
        uses: sagikazarmark/setup-please-action@v0
        with:
          output: all
          verbosity: debug
          save-logs: true
      
      - name: build
        run: plz build .//...
      
      # - name: store pnpm cache
      #   id: pnpm-cache-store
      #   uses: actions/cache/save@v4
      #   with:
      #     path: $PNPM_STORE_PATH
      #     key: ${{ steps.pnpm-cache-restore.outputs.cache-primary-key }}


