# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-os:
    runs-on: ubuntu-24.04
    steps:
    - name: Update OS
      run: sudo apt-get update
  
  build-flatbuffers:
    runs-on: ubuntu-24.04
    needs: update-os
    outputs:
      artifact: ${{ steps.flatc-upload-step.outputs.artifact-id }}
    steps:
    - uses: LIT-Protocol/artifact-exists-action@v0
      name: Check Flatbuffers Are Already Built
      id: check-flatbuffers-built
      with:
        name: flatc-distro
    - name: Build Flatbuffers
      if: "${{ steps.check-flatbuffers-built.outputs.exists == 'false' }}"
      run: |
        mkdir ./flatbuffers-source
        cd ./flatbuffers-source
        git clone https://github.com/google/flatbuffers.git --branch v24.3.25 --single-branch .
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        make -j
        make test
        sudo make install
    - name: Tar Flatbuffers
      if: "${{ steps.check-flatbuffers-built.outputs.exists == 'false' }}"
      run: |
        tar -cvf flatbuffers.tar \
          /usr/local/include/flatbuffers \
          /usr/local/lib/libflatbuffers.a \
          /usr/local/bin/flatc
    - uses: actions/upload-artifact@v4
      if: "${{ steps.check-flatbuffers-built.outputs.exists == 'false' }}"
      id: flatc-upload-step
      with:
        name: flatc-distro
        path: flatbuffers.tar
        if-no-files-found: error
        retention-days: 1
        compression-level: 0
        overwrite: true
  
  run-unit-tests:
    runs-on: ubuntu-24.04
    needs: build-flatbuffers

    strategy:
      matrix:
        node-version: [22.5.1]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: flatc-distro
      - name: Untar Flatbuffers
        run: sudo tar -xvf flatbuffers.tar -C /
      - name: Check Flatbuffers Location/Version
        run: |
          flatc --version
          which flatc
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4 
        with:
          version: 9.6.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm --recursive install
      - run: pnpm --recursive run test
      - run: pnpm --recursive run cover
