# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-os:
    runs-on: ubuntu-24.04
    steps:
    - name: Update OS
      run: sudo apt-get update
  
  install-flatbuffers:
    runs-on: ubuntu-24.04
    needs: update-os
    steps:
    - name: Install Flatbuffers
      run: |
        mkdir ./flatbuffers-source
        cd ./flatbuffers-source
        git clone https://github.com/google/flatbuffers.git --branch v24.3.25 --single-branch .
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        make -j
        make test
        sudo make install
        which flatc
        flatc --version
  
  check-flatbuffers-location:
    runs-on: ubuntu-24.04
    needs: install-flatbuffers
    steps:
    - name: Check Flatbuffers Location
      run: |
        which flatc
        exit 1

  build:
    runs-on: ubuntu-24.04
    needs: check-flatbuffers-location

    strategy:
      matrix:
        node-version: [22.5.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4 
      with:
        version: 9.6.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install Google Flatbuffers
      run: |
        sudo apt-get update
        sudo snap install flatbuffers
    - run: pnpm --recursive install
    - run: pnpm --recursive run test
    - run: pnpm --recursive run cover
